[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
collectible_vault = "Bk73CJxtKr2Z9X9sKUwEvoafHXSnX7xPpLUhT9ujLXwU"

[programs.devnet]
collectible_vault = "Bk73CJxtKr2Z9X9sKUwEvoafHXSnX7xPpLUhT9ujLXwU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
