[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
collectible_vault = "8G4KcKxZZmXikmw5i3irw9ogKWS2E61vMgwovcJ4tdbr"

[programs.localnet]
collectible_vault = "HsgWi9YLC6xGPkMyh3wKZysz2awKVas4BUKCQMeC5woR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
