[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
collectible_vault = "AhxqpDiUNUnFPZp8goT9YZv9H1Zhwf75RUsruiigu3T6"

[programs.localnet]
collectible_vault = "EWjqcPNsohKJykuHxBG6X6LVpRu1ki2uBRrnzRwtx4uh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
